### ISSUE TITLE
BlockchainLMDB::get_block_cumulative_difficulty -- difficulty not in db

### ISSUE THREAD

**Issue by osensei** [tewinget/bitmonero#27]
When trying to call the JSON RPC method "getlastblockheader" the daemon will show the error message "Attempt to get cumulative difficulty from height 441019 failed -- difficulty not in db" and will return an empty reply to the client. This is preventing the pool software from working.

**Comment by tewinget** [comment]
For now I need sleep, as I'm recovering from a bit of a cold, but I will look at this in the morning.  Thanks for the heads up!

**Comment by tewinget** [comment]
This should be fixed now.

**Comment by osensei** [comment]
Thanks Thomas! Unfortunately blockchain is not syncing now, and I get the following error from different peers with log level 1:

`
2015-Feb-21 02:42:24.678852 [P2P7]The miner transaction in block has invalid height: 445454, expected: 445453`

Also, if starting to sync from scratch I get the following:

```
2015-Feb-21 02:52:35.769336 Initializing core...
2015-Feb-21 02:52:35.769387 Loading blockchain...
2015-Feb-21 02:52:35.769869 Attempt to get timestamp from height 18446744073709550880 failed -- timestamp not in db
2015-Feb-21 02:52:35.770496 Mining has been stopped, 0 finished
2015-Feb-21 02:52:35.770622 ERROR /home/monero/bitmonero/src/daemon/daemon.cpp:300 Exception at [main], what=Attempt to get timestamp from height 18446744073709550880 failed -- timestamp not in db
```

And then it dies.

**Comment by tewinget** [comment]
Ugh, that's almost certainly the same issue.  I'll sort it next time I'm at
a proper computer.  Hopefully in the next few hours.
