### ISSUE TITLE
can't find lmdb.h during make

### ISSUE THREAD

**Issue by Gingeropolous** [tewinget/bitmonero#34]
i tried to build on new machine. did you rename something and forget to change something? saw the file is called lmdb_db.h, whereas the make is trying to find lmdb.h in the src folder.

**Comment by tewinget** [comment]
I'll check in a few...

**Comment by tewinget** [comment]
Fixed.  Apparently I didn't let the binaries fully link when I made sure it still built last time.  I'll be sure to lash myself accordingly.
